"""empty message

Revision ID: 85dcf4acc31c
Revises: 
Create Date: 2023-07-07 11:45:10.828315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dcf4acc31c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], name=op.f('fk_games_court_id_courts')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_player_games_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_games_player_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_games')
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('courts')
    # ### end Alembic commands ###
